# Generated by Django 4.2.1 on 2023-05-12 16:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0006_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
